stanzas:
  - type: webapp
    exec: ../aspico-api
    host: "localhost:8055"
    env:
      ENV: Production
      ASPICO_PUSH_URL: "http://localhost:1267/v0/register-cv"
    forward-env:
      - ASPICO_DB_PASSWORD
